### ISSUE TITLE
MobX

### ISSUE THREAD

**Issue by benjamingr** [joarwilk/typedef-converter#10]
Hey, would you be willing to maintain this works with MobX (https://github.com/mobxjs/mobx/issues/640) and support the official flow types?

**Comment by joarwilk** [comment]
Hey, the goal is to convert ~2000 missing flow type definitions so I won't have any time to work with individual libraries unfortunately. However, if you pass me the typescript definition (as one or many files) I'd love to use MobX as a reference project since it has some interesting syntax.

**Comment by benjamingr** [comment]
Sure https://github.com/mobxjs/mobx/tree/master/src/types

**Comment by benjamingr** [comment]
@joarwilk ?
