### ISSUE TITLE
PR: Adding tests

### ISSUE THREAD

**Issue by amilajack** [joarwilk/typedef-converter#6]
Would adding tests for this project be a welcome contribution?

**Comment by joarwilk** [comment]
Yes, absolutely!

The dream would be to have definition tests in the style of flow-typed's `run-tests`, so we can test the quality of the definition files.

**Comment by amilajack** [comment]
I see. Where can I see of those tests? It seems like the test command is [this](https://github.com/flowtype/flow-typed/blob/master/cli/package.json#L13). Is this something we're looking for?

**Comment by joarwilk** [comment]
Yeah thats the one! Here's the test suite for moment, as an example: https://github.com/flowtype/flow-typed/blob/master/definitions/npm/moment_v2.x.x/test_moment-v2.js

If we can leverage the tests already written in that repo I think we'd get a lot of work done for free.

It's more like a regression test, but I think it makes a lot of sense at this stage.

**Comment by amilajack** [comment]
Got it. I'll try adding support for these kinds of tests later today or over the weekend
